[package]
name = "native-render-sdl2"
version = "0.1.0"
edition = "2021"

[dependencies]
cocoa = "0.26.0"
libc = "0.2.158"
objc = "0.2.7"
raw-window-handle = "0.6.2"
sdl2 = {version = "0.37.0", features = ["raw-window-handle"]}
wgpu = "22.1.0"
